name: Create Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Build docker image
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: mv /home/ptg/actions-runner/_work/Partisan-Telegram-Android /home/ptg/actions-runner/_work/delete_me