name: Create Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Build docker image
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: mv ../.. ../to_delete